#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Ejecutando validaciones pre-commit...'

# Ejecutar lint-staged para los archivos modificados
npm run lint-staged

# Ejecutar pruebas
npm run test

# Verificar el formato
npm run format:check

# Si todo está bien, permitir el commit
echo '✅ Las validaciones pre-commit han pasado exitosamente!' 